import os
from tkinter import *
from tkinter import ttk
def AntiOpera():
    os.system('start antivirus.py')
def Stop():
    os.system("taskkill /f /IM opera.exe")
    os.system("taskkill /f /IM python.exe")
root = Tk()
root.title("i")
root.geometry("500x500")
root.resizable(width=500,height=500)
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="Antivirus")
label.pack()
btn1 = ttk.Button(text="    start   ", command=AntiOpera)
btn1.pack(anchor="nw",padx=210, pady=0)
btn1 = ttk.Button(text="    stop    ", command=Stop)
btn1.pack(anchor="nw",padx=210, pady=5)
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="Stopping the program can lead to closing all programs on python!")
label.pack()
root.mainloop()
